config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [:index, :show, :new, :destroy]
  resources :feeds, only: [:index, :show, :new, :destroy]
  resources :posts, only: [:show, :new, :destroy]
  resources :comments, only: [:show, :new, :destroy]

  namespace :admin do
    get '/', to: 'static#dashboard', as: :dashboard
    resource  :session, only: %w(new create destroy)
    resources :users, only: %w(index show edit update)
    resources :pages
    resources :feeds
    resources :posts
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :parent, polymorphic: true
  scope :by_parent, lambda { |parent_id| where(parent_id: parent_id) unless parent_id.nil? }
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :posts
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :comments, as: :parent
  validates :slug, uniqueness: true, presence: true, exclusion: {in: %w[signup login]}

  before_validation :generate_slug

  # def to_param
  #   slug # or "#{id}-#{name}".parameterize
  # end

  def generate_slug
    self.slug ||= name.parameterize
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :feed
  belongs_to :author, class_name: "User"
  has_many :comments, as: :parent
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize!
    redirect_to new_admin_session_url, alert: "Not authorized" if current_user.nil?
  end

  before_action :authorize!
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_parent, only: [:new, :create, :show]

  def index
    @comments = Comment.by_parent(params[:parent])
  end

  def show
  end

  def new
    @comment = @parent.comments.new
  end

  def edit
  end

  def create
    @comment = @parent.comments.new(comment_params)

    if @comment.save
      redirect_to admin_comment_url, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to admin_comment_url, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to admin_comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent
    case params[:type]
    when "Post"
      @parent = Post.find(params[:parent])
    when "Feed"
      @parent = Feed.find(params[:parent])
    end

  end

  def comment_params
    params.require(:comment).permit(:author_id, :parent_id, :parent_type, :slug, :content)
  end
end

app/controllers/admin/feeds_controller.rb
class Admin::FeedsController < Admin::AdminController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to admin_feed_url(@feed), notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to admin_feed_url(@feed), notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feed.destroy
    redirect_to admin_feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :slug, :body)
    end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::AdminController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to admin_page_url, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to admin_page_url, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to admin_pages_url, notice: 'Page was successfully destroyed.'
  end

  private
    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :slug, :body)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @feeds = Feed.all
    @users = User.all
  end

  def edit
    @feeds = Feed.all
    @users = User.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to admin_post_url(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to admin_post_url(@post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:feed_id, :author_id, :slug, :title, :body)
    end
end

app/controllers/admin/static_controller.rb
class Admin::StaticController < Admin::AdminController
  def dashboard
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.order('last_name ASC')
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  def cancel_selected_print_plan
    @user = User.find(params[:id])

    @user.update(selected_print_plan: nil)

    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/_form.html.haml
= form_for [:admin, page], html: { class: 'form-horizontal', role: 'form' } do |form|
  - if page.errors.any?
    #error_explanation
      %h2
        = pluralize(page.errors.count, "error")
        prohibited this page from being saved:
      %ul
        - page.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :title, class: 'form-control'
  .form-group
    = form.label :slug, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :slug, class: 'form-control'
  .form-group
    = form.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_area :body, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = form.submit class: 'btn btn-default'

app/views/admin/pages/edit.html.haml
%h1 Editing Page
= render 'form', page: @page
= link_to 'Show', [:admin, @page]
|
= link_to 'Back', admin_pages_path

app/views/admin/pages/index.html.haml
%ol.breadcrumb
%h3 Pages
%table.table
  %thead
    %tr
      %th Title
      %th Slug
      %th Body
      %th{colspan: "3"}
  %tbody
    - @pages.each do |page|
      %tr
        %td= page.title
        %td= page.slug
        %td= page.body
        %td= link_to 'Show', [:admin, page]
        %td= link_to 'Edit', edit_admin_page_path(page)
        %td= link_to 'Destroy', [:admin, page], method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Page', new_admin_page_path

app/views/admin/pages/new.html.haml
%h1 New Page
= render 'form', page: @page
= link_to 'Back', admin_pages_path

app/views/admin/pages/show.html.haml
%p
  %strong Title:
  = @page.title
%p
  %strong Slug:
  = @page.slug
%p
  %strong Body:
  = @page.body
= link_to "Comments", {controller: "admin/comments", action: "index", parent: @post.id, type: @post.class }
|
= link_to 'Edit', edit_admin_page_path(@page)
|
= link_to 'Back', admin_pages_path

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %link{:href => "../../assets/ico/favicon.png", :rel => "shortcut icon"}/
    %title Mandy Ream Administration
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => admin_dashboard_path} Home
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Users', admin_users_path
            %li
              = link_to 'Pages', admin_pages_path
            %li
              = link_to 'Feeds', admin_feeds_path
            %li
              = link_to 'Posts', admin_posts_path
            %li
              = link_to 'Log Out', admin_session_path, method: :delete
    .container.main-content
      - flash.each do |type, msg|
        %div{class: "alert alert-#{type}"}
          %strong= msg
      = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mandy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pages/index.html.haml
%p#notice= notice
%h1 Pages
%table
  %thead
    %tr
      %th Title
      %th Slug
      %th Body
      %th{colspan: "3"}
  %tbody
    - @pages.each do |page|
      %tr
        %td= page.title
        %td= page.slug
        %td= page.body
        %td= link_to 'Show', page
        %td= link_to 'Edit', edit_page_path(page)
        %td= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Page', new_page_path

app/views/pages/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @page.title
%p
  %strong Slug:
  = @page.slug
%p
  %strong Body:
  = @page.body
%p
  %strong Type:
  = @page.type
= link_to 'Edit', edit_page_path(@page)
|
= link_to 'Back', pages_path