config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [:index, :show, :new, :destroy]
  resources :feeds, only: [:index, :show, :new, :destroy]
  resources :posts, only: [:show, :new, :destroy]
  resources :comments, only: [:show, :new, :destroy]

  namespace :admin do
    get '/', to: 'static#dashboard', as: :dashboard
    resource  :session, only: %w(new create destroy)
    resources :users, only: %w(index show edit update)
    resources :pages
    resources :feeds
    resources :posts
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :parent, polymorphic: true
  scope :by_parent, lambda { |parent_id| where(parent_id: parent_id) unless parent_id.nil? }
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :posts
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :comments, as: :parent
  validates :slug, uniqueness: true, presence: true, exclusion: {in: %w[signup login]}

  before_validation :generate_slug

  # def to_param
  #   slug # or "#{id}-#{name}".parameterize
  # end

  def generate_slug
    self.slug ||= name.parameterize
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :feed
  belongs_to :author, class_name: "User"
  has_many :comments, as: :parent
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize!
    redirect_to new_admin_session_url, alert: "Not authorized" if current_user.nil?
  end

  before_action :authorize!
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_parent, only: [:new, :create, :show]

  def index
    @comments = Comment.by_parent(params[:parent])
  end

  def show
  end

  def new
    @comment = @parent.comments.new
  end

  def edit
  end

  def create
    @comment = @parent.comments.new(comment_params)

    if @comment.save
      redirect_to admin_comment_url, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to admin_comment_url, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to admin_comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent
    case params[:type]
    when "Post"
      @parent = Post.find(params[:parent])
    when "Feed"
      @parent = Feed.find(params[:parent])
    end

  end

  def comment_params
    params.require(:comment).permit(:author_id, :parent_id, :parent_type, :slug, :content)
  end
end

app/controllers/admin/feeds_controller.rb
class Admin::FeedsController < Admin::AdminController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to admin_feed_url(@feed), notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to admin_feed_url(@feed), notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feed.destroy
    redirect_to admin_feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :slug, :body)
    end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::AdminController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to admin_page_url, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to admin_page_url, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to admin_pages_url, notice: 'Page was successfully destroyed.'
  end

  private
    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :slug, :body)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @feeds = Feed.all
    @users = User.all
  end

  def edit
    @feeds = Feed.all
    @users = User.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to admin_post_url(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to admin_post_url(@post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:feed_id, :author_id, :slug, :title, :body)
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::AdminController
  # skip_before_action :authorize!, only: %w(new create)

  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_dashboard_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_admin_session_url, notice: "Logged out!"
  end
end

app/controllers/admin/static_controller.rb
class Admin::StaticController < Admin::AdminController
  def dashboard
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.order('last_name ASC')
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  def cancel_selected_print_plan
    @user = User.find(params[:id])

    @user.update(selected_print_plan: nil)

    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/for_later/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def show
  end
end

app/controllers/for_later/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/comments/_comment.html.haml
%tr
  %td= link_to comment.author.full_name, admin_user_path(comment.author)
  %td= link_to comment.parent.slug, polymorphic_path([:admin, comment.parent])
  %td= comment.content.truncate(30)
  %td= link_to 'Show', [:admin, comment]
  %td= link_to 'Edit', edit_admin_comment_path(comment)
  %td= link_to 'Destroy', [:admin, comment], method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/comments/_form.html.haml
= form_for [:admin, comment], html: { class: 'form-horizontal', role: 'form' } do |form|
  - if comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, "error")
        prohibited this comment from being saved:
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label "Author", class: 'col-sm-2 control-label'
    .col-sm-10
      = "#{current_user.full_name}"
  .form-group
    = form.label "Parent", class: 'col-sm-2 control-label'
    .col-sm-10
      = link_to "#{parent.slug}", polymorphic_path([:admin, parent])
  .form-group
    = form.label :slug, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :slug, class: 'form-control'
  .form-group
    = form.label :content, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_area :content, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = form.submit class: 'btn btn-default'

app/views/admin/comments/index.html.haml
- if @comments.count > 0
  %h1 Comments for #{@comments.first.parent.title}
- else
  %h1 Comments
%table.table
  %thead
    %tr
      %th Author
      %th Parent
      %th Content
      %th{colspan: "3"}
  %tbody
    = render partial: "comment", collection: @comments
%br/
= link_to 'New Comment', new_admin_comment_path(parent: @comments.first.parent_id, type: @comments.first.parent_type)

app/views/admin/comments/new.html.haml
%h1 New Comment on #{@parent.slug}
= render 'form', {comment: @comment, parent: @parent}
= link_to 'Back', admin_comments_path(parent: @parent.id)

app/views/admin/comments/show.html.haml
%p
  %strong Author:
  = link_to @comment.author.full_name, admin_user_path(@comment.author)
%p
  %strong Parent:
  = link_to @comment.parent.slug, polymorphic_path([:admin, @comment.parent])
%p
  %strong Slug:
  = @comment.slug
%p
  %strong Content:
  = @comment.content.truncate(30)
= link_to 'Edit', edit_admin_comment_path(@comment)
|
= link_to 'Back', admin_comments_path(parent: @comment.parent.id)

app/views/admin/users/edit.html.haml
%h1 Editing #{@user.email}

= form_for [:admin, @user], html: { class: 'form-horizontal', role: 'form' } do |f|
  .form-group
    = f.label :first_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :email, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :password, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.password_field :password_confirmation, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-default'

app/views/admin/users/index.html.haml
%ol.breadcrumb

%h3 Users
%table.table
  %thead
    %tr
      %th First Name
      %th Last Name
      %th Email
      %th Actions
  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td
          = link_to 'Details', admin_user_path(user)

app/views/admin/users/show.html.haml
%p
  %strong First Name:
  = @user.first_name
%p
  %strong Last Name:
  = @user.last_name
%p
  %strong Email:
  = @user.email
%p
  %strong Admin:
  = @user.admin
= link_to 'Edit', edit_admin_user_path(@user)
|
= link_to 'Back', admin_users_path

app/views/comments/index.html.haml
%p#notice= notice
%h1 Comments
%table
  %thead
    %tr
      %th Author
      %th Parent
      %th Parent type
      %th Slug
      %th Content
      %th{colspan: "3"}
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.author_id
        %td= comment.parent_id
        %td= comment.parent_type
        %td= comment.slug
        %td= comment.content
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_comment_path

app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong Author:
  = @comment.author_id
%p
  %strong Parent:
  = @comment.parent_id
%p
  %strong Parent type:
  = @comment.parent_type
%p
  %strong Slug:
  = @comment.slug
%p
  %strong Content:
  = @comment.content
= link_to 'Edit', edit_comment_path(@comment)
|
= link_to 'Back', comments_path