config/routes.rb
Rails.application.routes.draw do
  resources :pages, only: [:index, :show, :new, :destroy]
  resources :feeds, only: [:index, :show, :new, :destroy]
  resources :posts, only: [:show, :new, :destroy]
  resources :comments, only: [:show, :new, :destroy]

  namespace :admin do
    get '/', to: 'static#dashboard', as: :dashboard
    resource  :session, only: %w(new create destroy)
    resources :users, only: %w(index show edit update)
    resources :pages
    resources :feeds
    resources :posts
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :parent, polymorphic: true
  scope :by_parent, lambda { |parent_id| where(parent_id: parent_id) unless parent_id.nil? }
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :posts
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :comments, as: :parent
  validates :slug, uniqueness: true, presence: true, exclusion: {in: %w[signup login]}

  before_validation :generate_slug

  # def to_param
  #   slug # or "#{id}-#{name}".parameterize
  # end

  def generate_slug
    self.slug ||= name.parameterize
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :feed
  belongs_to :author, class_name: "User"
  has_many :comments, as: :parent
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize!
    redirect_to new_admin_session_url, alert: "Not authorized" if current_user.nil?
  end

  before_action :authorize!
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_parent, only: [:new, :create, :show]

  def index
    @comments = Comment.by_parent(params[:parent])
  end

  def show
  end

  def new
    @comment = @parent.comments.new
  end

  def edit
  end

  def create
    @comment = @parent.comments.new(comment_params)

    if @comment.save
      redirect_to admin_comment_url, notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to admin_comment_url, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to admin_comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent
    case params[:type]
    when "Post"
      @parent = Post.find(params[:parent])
    when "Feed"
      @parent = Feed.find(params[:parent])
    end

  end

  def comment_params
    params.require(:comment).permit(:author_id, :parent_id, :parent_type, :slug, :content)
  end
end

app/controllers/admin/feeds_controller.rb
class Admin::FeedsController < Admin::AdminController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to admin_feed_url(@feed), notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to admin_feed_url(@feed), notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feed.destroy
    redirect_to admin_feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :slug, :body)
    end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::AdminController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to admin_page_url, notice: 'Page was successfully created.'
    else
      render :new
    end
  end

  def update
    if @page.update(page_params)
      redirect_to admin_page_url, notice: 'Page was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @page.destroy
    redirect_to admin_pages_url, notice: 'Page was successfully destroyed.'
  end

  private
    def set_page
      @page = Page.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:title, :slug, :body)
    end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
    @feeds = Feed.all
    @users = User.all
  end

  def edit
    @feeds = Feed.all
    @users = User.all
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to admin_post_url(@post), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to admin_post_url(@post), notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:feed_id, :author_id, :slug, :title, :body)
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::AdminController
  # skip_before_action :authorize!, only: %w(new create)

  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_dashboard_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_admin_session_url, notice: "Logged out!"
  end
end

app/controllers/admin/static_controller.rb
class Admin::StaticController < Admin::AdminController
  def dashboard
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.order('last_name ASC')
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  def cancel_selected_print_plan
    @user = User.find(params[:id])

    @user.update(selected_print_plan: nil)

    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email,
                                 :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/for_later/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Feed.all
  end

  def show
  end
end

app/controllers/for_later/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
  end
end

app/controllers/for_later/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/feeds/_form.html.haml
= form_for [:admin, feed], html: { class: 'form-horizontal', role: 'form' } do |form|
  - if feed.errors.any?
    #error_explanation
      %h2
        = pluralize(feed.errors.count, "error")
        prohibited this feed from being saved:
      %ul
        - feed.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :title, class: 'form-control'
  .form-group
    = form.label :slug, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :slug, class: 'form-control'
  .form-group
    = form.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_area :body, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = form.submit class: 'btn btn-default'

app/views/admin/feeds/edit.html.haml
%h1 Editing Feed
= render 'form', feed: @feed
= link_to 'Show', [:admin, @feed]
|
= link_to 'Back', admin_feeds_path

app/views/admin/feeds/index.html.haml
%h1 Feeds
%table.table
  %thead
    %tr
      %th Title
      %th Slug
      %th Body
      %th{colspan: "3"}
  %tbody
    - @feeds.each do |feed|
      %tr
        %td= feed.title
        %td= feed.slug
        %td= feed.body
        %td= link_to 'Show', [:admin, feed]
        %td= link_to 'Edit', edit_admin_feed_url(feed)
        %td= link_to 'Destroy', [:admin, feed], method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Feed', new_admin_feed_path

app/views/admin/feeds/new.html.haml
%h1 New Feed
= render 'form', feed: @feed
= link_to 'Back', admin_feeds_path

app/views/admin/feeds/show.html.haml
%p
  %strong Title:
  = @feed.title
%p
  %strong Slug:
  = @feed.slug
%p
  %strong Body:
  = @feed.body
= link_to 'Edit', edit_admin_feed_path(@feed)
|
= link_to 'Back', admin_feeds_path

app/views/admin/posts/_form.html.haml
= form_for [:admin, post], html: { class: 'form-horizontal', role: 'form' } do |form|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message
  .form-group
    = form.label :feed_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.collection_select :feed_id, @feeds.order(:title),:id,:title, include_blank: true
  .form-group
    = form.label :author_id, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.collection_select :author_id, @users.order(:first_name), :id, :full_name, include_blank: true
      -# = form.number_field :author_id, class: 'form-control'
  .form-group
    = form.label :slug, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :slug, class: 'form-control'
  .form-group
    = form.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_field :title, class: 'form-control'
  .form-group
    = form.label :body, class: 'col-sm-2 control-label'
    .col-sm-10
      = form.text_area :body, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = form.submit class: 'btn btn-default'


-# = form_for [:admin, @manager], html: { class: 'form-horizontal', role: 'form' } do |form|
-#   .form-group
-#     = form.label :email, class: 'col-sm-2 control-label'
-#     .col-sm-10
-#       = form.email_field :email, class: 'form-control'
-#   .form-group
-#     = form.label :password, class: 'col-sm-2 control-label'
-#     .col-sm-10
-#       = form.password_field :password, class: 'form-control'
-#   .form-group
-#     = form.label :password_confirmation, class: 'col-sm-2 control-label'
-#     .col-sm-10
-#       = form.password_field :password_confirmation, class: 'form-control'
-#   - if current_manager.admin?
-#     .form-group
-#       .col-sm-offset-2.col-sm-10
-#         .checkbox
-#           %label
-#             = form.check_box :admin, disabled: @manager == current_manager
-#             Administrative Access
  .form-group
    .col-sm-offset-2.col-sm-10
      = form.submit class: 'btn btn-default'

app/views/admin/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', admin_posts_path

app/views/admin/posts/index.html.haml
%h1 Posts
%table.table
  %thead
    %tr
      %th Title
      %th Feed
      %th Author
      %th Slug
      %th Body
      %th{colspan: "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.feed.title
        %td= post.author.full_name
        %td= post.slug
        %td= post.body.truncate(30)
        %td= link_to 'Show', [:admin, post]
        %td= link_to 'Edit', edit_admin_post_path(post)
        %td= link_to 'Destroy', [:admin, post], method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_admin_post_path

app/views/admin/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', admin_posts_path

app/views/admin/posts/show.html.haml
%p
  %strong Feed:
  = link_to @post.feed.title, admin_feed_path(@post.feed)
%p
  %strong Author:
  = link_to @post.author.full_name, admin_user_path(@post.author)
%p
  %strong Slug:
  = @post.slug
%p
  %strong Title:
  = @post.title
%p
  %strong Body:
  = @post.body
= link_to "Comments", {controller: "admin/comments", action: "index", parent: @post.id, type: @post.class }
|
= link_to 'Edit', edit_admin_post_path(@post)
|
= link_to 'Back', admin_posts_path

app/views/feeds/_form.html.haml
= form_with(model: feed, local: true) do |form|
  - if feed.errors.any?
    #error_explanation
      %h2
        = pluralize(feed.errors.count, "error")
        prohibited this feed from being saved:
      %ul
        - feed.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :slug
    = form.text_field :slug
  .field
    = form.label :body
    = form.text_area :body
  .field
    = form.label :type
    = form.text_field :type
  .actions
    = form.submit

app/views/feeds/edit.html.haml
%h1 Editing Feed
= render 'form', feed: @feed
= link_to 'Show', @feed
|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
%p#notice= notice
%h1 Feeds
%table
  %thead
    %tr
      %th Title
      %th Slug
      %th Body
      %th Type
      %th{colspan: "3"}
  %tbody
    - @feeds.each do |feed|
      %tr
        %td= feed.title
        %td= feed.slug
        %td= feed.body
        %td= feed.type
        %td= link_to 'Show', feed
        %td= link_to 'Edit', edit_feed_path(feed)
        %td= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Feed', new_feed_path

app/views/feeds/new.html.haml
%h1 New Feed
= render 'form', feed: @feed
= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @feed.title
%p
  %strong Slug:
  = @feed.slug
%p
  %strong Body:
  = @feed.body
%p
  %strong Type:
  = @feed.type
= link_to 'Edit', edit_feed_path(@feed)
|
= link_to 'Back', feeds_path

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :feed_id
    = form.text_field :feed_id
  .field
    = form.label :author_id
    = form.number_field :author_id
  .field
    = form.label :slug
    = form.text_field :slug
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :body
    = form.text_area :body
  .actions
    = form.submit

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%p#notice= notice
%h1 Posts
%table
  %thead
    %tr
      %th Feed
      %th Author
      %th Slug
      %th Title
      %th Body
      %th{colspan: "3"}
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.feed
        %td= post.author_id
        %td= post.slug
        %td= post.title
        %td= post.body
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New Post
= render 'form', post: @post
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
%p
  %strong Feed:
  = @post.feed
%p
  %strong Author:
  = @post.author_id
%p
  %strong Slug:
  = @post.slug
%p
  %strong Title:
  = @post.title
%p
  %strong Body:
  = @post.body
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path